fit <- tabItem('fit',
               fluidPage(
                 box(width = 12,
                     selectInput("model", label = "Selecht Model",
                                 choices = c("sGARCH",
                                             "fGARCH",
                                             "eGARCH",
                                             "gjrGARCH",
                                             "apGARCH",
                                             "iGARCH",
                                             "csGARCH"))),
                 fluidRow(
                   box(width = 6,
                       numericInput("q",label = "Select q",
                                    value = 1,
                                    min = 0, 
                                    max = 100, 
                                    step = 1)),
                   box(width = 6,
                       numericInput("p", label = "Select p",
                                    value = 1,
                                    min = 0,
                                    max = 100,
                                    step = 1))),
                 fluidRow(
                   box(width = 4,
                       numericInput("ar",label = "Select ar",
                                    value = 1,
                                    min = 0, 
                                    max = 100, 
                                    step = 1)),
                   box(width = 4,
                       numericInput("ma", label = "Select ma",
                                    value = 1,
                                    min = 0,
                                    max = 100,
                                    step = 1)),
                   box(width = 4,
                       selectInput("inc_mean", label = "Should the mean be included?",
                                   choices = c("True" = TRUE, 
                                               "False" = FALSE)))), # end fluidrow
                 box(width = 12,
                     selectInput("dist_model", label = "Select distribution",
                                 choices = c("Normal" = "norm",
                                             "Skewed Normal" = "snorm",
                                             "Student-t" = "std",
                                             "Skewed Student-t" = "sstd",
                                             "Generalized error" = "ged",
                                             "Skewed generalized error" = "sged",
                                             "Inversed gaussian" = "nig",
                                             "Generalized hyperbolic" = "ghyp",
                                             "Johnson's SU" = "jsu"))),
                 box(width = 6,
                     numericInput("os_fit", label = "Select out of sample", 
                                  value = 0, min = 0, max = 1000, step = 1)),
                 box(width = 6,
                     selectInput("solver", label = "Select solver",
                                 choices = c("nlminb",
                                             "solnp",
                                             "lbfgs",
                                             "gosolnp",
                                             "nloptr",
                                             "hybrid"), 
                                 selected = "solnp")),
                 
                 box(width = 12,
                     verbatimTextOutput("print_modfit")),
                 box(width = 12,
                     numericInput("fit_plot_num", "Select plot number", value = 1,
                                  min = 1, max = 12, step = 1)),
                 box(width = 12,
                     plotOutput("plot_modfit"))
               ) # end fluidpage
)